# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dpa-newslab.github.io/dpa-trustproject
title: dpa - Trust Project 
email: martin.virtel@dpa-info.com
author: Martin Virtel
description: > # "Write an awesome description for your new site here. 
  Information about the Trust Project &amp; dpa Deutsche Presseagantur
copyright: '(c) 2017 dpa-infocom GmbH'
credits: 'dpa-newslab'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 
